# Generated by Django 6.1 on 2026-08-17 09:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PickupRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='路径名称')),
                ('source_filename', models.CharField(max_length=255, verbose_name='原始文件名')),
                ('source_sha256', models.CharField(max_length=64, verbose_name='文件摘要')),
                ('color', models.CharField(default='#1677ff', max_length=7, verbose_name='路径颜色')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='导入时间')),
            ],
            options={
                'verbose_name': '取物路径',
                'verbose_name_plural': '取物路径',
                'db_table': 'pickup_route',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoutePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_no', models.PositiveIntegerField(verbose_name='轨迹点顺序')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='经度')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='纬度')),
                ('description', models.CharField(max_length=500, verbose_name='说明信息')),
                ('status', models.CharField(choices=[('carrier', '物品已取'), ('notget', '物品未取')], max_length=10, verbose_name='轨迹点状态')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='pickup_routes.pickuproute', verbose_name='所属路径')),
            ],
            options={
                'verbose_name': '轨迹点',
                'verbose_name_plural': '轨迹点',
                'db_table': 'route_point',
                'ordering': ['sequence_no'],
                'constraints': [models.UniqueConstraint(fields=('route', 'sequence_no'), name='unique_route_point_sequence')],
            },
        ),
    ]
